let b = 20
let a =40
console.log("The value of a is ",a," and value of b is ",b)
console.log("<----Arithmetic----->")
console.log("a+b = ",a+b)
console.log("a-b = ",a-b)
console.log("a*b = ",a*b)
console.log("a/b = ",a/b)
console.log("a%b = ",a%b)
console.log("<----Relational----->")
console.log("a<b = ",a<b)
console.log("a>b = ",a>b)
console.log("a<=b = ",a<=b)
console.log("a>=b = ",a>=b)
console.log("a!=b = ",a!=b)
console.log("<----Logical----->")
console.log("a&&b = ",a&&b)
console.log("a||b = ",a||b)
console.log("a|b = ",a|b)
console.log("<----Increment and Decrement----->")
console.log("a,, = ",a++)
console.log("a-- = ",a--)
console.log("<----Bitwise----->")
console.log("a&b = ",a&b)
console.log("a|b = ",a|b)
console.log("a^b = ",a^b)
console.log("a<<b = ",a<<b)
console.log("a>>b = ",a>>b)
console.log("~a = ", ~a)
console.log("<----Conditional----->")
console.log("If a<b :")
a<b?console.log("True"):console.log("False")